//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDM.DocFile.MLGWAddrLookup {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MLGWAddrLookup.MLGWSoap")]
    public interface MLGWSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lookUpAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string lookUpAddress(string accountNumber, string address);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MLGWSoapChannel : EDM.DocFile.MLGWAddrLookup.MLGWSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MLGWSoapClient : System.ServiceModel.ClientBase<EDM.DocFile.MLGWAddrLookup.MLGWSoap>, EDM.DocFile.MLGWAddrLookup.MLGWSoap {
        
        public MLGWSoapClient() {
        }
        
        public MLGWSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MLGWSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MLGWSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MLGWSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string lookUpAddress(string accountNumber, string address) {
            return base.Channel.lookUpAddress(accountNumber, address);
        }
    }
}
